# Generated by Django 3.2 on 2021-05-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_fichier_commentaire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichier',
            options={'ordering': ['user']},
        ),
        migrations.AddField(
            model_name='fichier',
            name='user',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
