# Generated by Django 3.2 on 2021-05-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=250)),
                ('finess', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
    ]
